const questionData = [
  {
    question: "What is the speed of light?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the charge of an electron?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is Newton's second law?",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the atomic number of hydrogen?",
    subject: "Chemistry",
    topic: "Atomic Structure",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the chemical formula of water?",
    subject: "Chemistry",
    topic: "Chemical Bonding",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of converting sugar into energy called?",
    subject: "Chemistry",
    topic: "Biochemistry",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the capital of France?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the highest mountain in the world?",
    subject: "Geography",
    topic: "Physical Geography",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of water cycle?",
    subject: "Geography",
    topic: "Environmental Geography",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What does HTML stand for?",
    subject: "Computer Science",
    topic: "Web Development",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the time complexity of binary search?",
    subject: "Computer Science",
    topic: "Algorithms",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is polymorphism in Object Oriented Programming?",
    subject: "Computer Science",
    topic: "Programming Concepts",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the principle of superposition?",
    subject: "Physics",
    topic: "Waves",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is Ohm's law?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the atomic number of helium?",
    subject: "Chemistry",
    topic: "Atomic Structure",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the chemical formula of carbon dioxide?",
    subject: "Chemistry",
    topic: "Chemical Bonding",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of photosynthesis?",
    subject: "Chemistry",
    topic: "Biochemistry",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the capital of Japan?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the longest river in the world?",
    subject: "Geography",
    topic: "Physical Geography",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of erosion?",
    subject: "Geography",
    topic: "Environmental Geography",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What does CSS stand for?",
    subject: "Computer Science",
    topic: "Web Development",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the time complexity of quick sort?",
    subject: "Computer Science",
    topic: "Algorithms",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is inheritance in Object Oriented Programming?",
    subject: "Computer Science",
    topic: "Programming Concepts",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the principle of conservation of momentum?",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the law of reflection?",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the law of universal gravitation?",
    subject: "Physics",
    topic: "Gravity",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Atomic Structure",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the chemical formula of methane?",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of fermentation?",
    subject: "Chemistry",
    topic: "Biochemistry",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What is the capital of Germany?",
    subject: "Geography",
    topic: "World Capitals",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the largest desert in the world?",
    subject: "Geography",
    topic: "Physical Geography",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is the process of plate tectonics?",
    subject: "Geography",
    topic: "Geology",
    difficulty: "Hard",
    marks: 15,
  },
  {
    question: "What does HTTP stand for?",
    subject: "Computer Science",
    topic: "Web Development",
    difficulty: "Easy",
    marks: 5,
  },
  {
    question: "What is the time complexity of merge sort?",
    subject: "Computer Science",
    topic: "Algorithms",
    difficulty: "Medium",
    marks: 10,
  },
  {
    question: "What is encapsulation in Object Oriented Programming?",
    subject: "Computer Science",
    topic: "Programming Concepts",
    difficulty: "Hard",
    marks: 15,
  },
];

module.exports = questionData;
